var pregrado = [
  { code: "2520", name: "ADMINISTRACIÓN DE EMPRESAS"},
  { code: "2523", name: "ANTROPOLOGÍA"},
  { code: "2529", name: "ANTROPOLOGÍA - PROGRAMA ESPECIAL DE ADMISION POR ÁREAS DEL CONOCIMIENTO"},
  { code: "2506", name: "ARQUITECTURA"},
  { code: "2507", name: "ARTES PLÁSTICAS"},
  { code: "2513", name: "BIOLOGÍA"},
  { code: "2538", name: "CIENCIA POLÍTICA"},
  { code: "2508", name: "CINE Y TELEVISIÓN"},
  { code: "2521", name: "CONTADURÍA PÚBLICA"},
  { code: "DTS" , name: "CRÉDITOS PRIMER PLAN PARA DOBLE TITULACIÓN"},
  { code: "2539", name: "DERECHO"},
  { code: "2509", name: "DISEÑO GRÁFICO"},
  { code: "2510", name: "DISEÑO INDUSTRIAL"},
  { code: "2522", name: "ECONOMÍA"},
  { code: "2540", name: "ENFERMERÍA"},
  { code: "2526", name: "ESPAÑOL Y FILOLOGÍA CLÁSICA"},
  { code: "2514", name: "ESTADÍSTICA"},
  { code: "2534", name: "ESTUDIOS LITERARIOS"},
  { code: "2515", name: "FARMACIA"},
  { code: "2528", name: "FILOLOGÍA E IDIOMAS - ESPAÑOL Y HUMANIDADES CLÁSICAS"},
  { code: "2524", name: "FILOLOGÍA E IDIOMAS ALEMÁN"},
  { code: "2525", name: "FILOLOGÍA E IDIOMAS FRANCÉS"},
  { code: "2527", name: "FILOLOGÍA E IDIOMAS INGLÉS"},
  { code: "2530", name: "FILOSOFÍA"},
  { code: "2516", name: "FÍSICA"},
  { code: "2550", name: "FISIOTERAPIA"},
  { code: "2551", name: "FONOAUDIOLOGÍA"},
  { code: "2531", name: "GEOGRAFÍA"},
  { code: "2757", name: "GEOGRAFÍA - PROGRAMA ESPECIAL DE ADMISIÓN POR ÁREAS DEL CONOCIMIENTO"},
  { code: "2517", name: "GEOLOGÍA"},
  { code: "2532", name: "HISTORIA"},
  { code: "2541", name: "INGENIERÍA AGRÍCOLA"},
  { code: "2505", name: "INGENIERÍA AGRONÓMICA"},
  { code: "2364", name: "INGENIERÍA AGRONÓMICA - PRO. ESPECIAL DE ADMISION POR ÁREAS DE CONOCIMIENTO"},
  { code: "2542", name: "INGENIERÍA CIVIL"},
  { code: "2543", name: "INGENIERÍA DE SISTEMAS"},
  { code: "2879", name: "INGENIERÍA DE SISTEMAS Y COMPUTACIÓN"},
  { code: "2544", name: "INGENIERÍA ELÉCTRICA"},
  { code: "2545", name: "INGENIERÍA ELECTRÓNICA"},
  { code: "2546", name: "INGENIERÍA INDUSTRIAL"},
  { code: "2547", name: "INGENIERÍA MECÁNICA"},
  { code: "2548", name: "INGENIERÍA MECATRÓNICA"},
  { code: "2549", name: "INGENIERÍA QUÍMICA"},
  { code: "2533", name: "LINGÜISTICA"},
  { code: "2837", name: "LINGÜÍSTICA"},
  { code: "2518", name: "MATEMÁTICAS"},
  { code: "2552", name: "MEDICINA"},
  { code: "2555", name: "MEDICINA VETERINARIA"},
  { code: "2511", name: "MÚSICA"},
  { code: "2512", name: "MÚSICA INSTRUMENTAL"},
  { code: "2553", name: "NUTRICIÓN Y DIETÉTICA"},
  { code: "2557", name: "ODONTOLOGÍA"},
  { code: "PEL" , name: "PROGRAMA DE ELECTIVAS (L)"},
  { code: "2535", name: "PSICOLOGÍA"},
  { code: "2519", name: "QUÍMICA"},
  { code: "2536", name: "SOCIOLOGÍA"},
  { code: "2554", name: "TERAPIA OCUPACIONAL"},
  { code: "2537", name: "TRABAJO SOCIAL"},
  { code: "2556", name: "ZOOTECNIA"}
]
module.exports = {
  pregrado: pregrado
}
